### ISSUE TITLE
TypeError: Retry.__init__() got an unexpected keyword argument 'backoff_max'

### ISSUE THREAD

**Issue by rth** [databricks/databricks-sql-python#411]
In the latest version on main there seem to be a regression, where,
```py
    import os
    from databricks import sql as databricks_sql

    db = databricks_sql.connect(
        server_hostname=os.getenv("DATABRICKS_SERVER_HOSTNAME"),
        http_path=os.getenv("DATABRICKS_HTTP_PATH"),
        access_token=os.getenv("DATABRICKS_TOKEN"),
    )
```
Produces
```py
Traceback (most recent call last):
  File "", line 8, in main
    db = databricks_sql.connect(
  File "databricks/sql/__init__.py", line 88, in connect
    from .client import Connection
  File "databricks/sql/client.py", line 19, in <module>
    from databricks.sql.thrift_backend import ThriftBackend
  File "databricks/sql/thrift_backend.py", line 29, in <module>
    from databricks.sql.utils import (
  File "databricks/sql/utils.py", line 17, in <module>
    from databricks.sql.cloudfetch.download_manager import ResultFileDownloadManager
  File "databricks/sql/cloudfetch/download_manager.py", line 6, in <module>
    from databricks.sql.cloudfetch.downloader import (
  File "databricks/sql/cloudfetch/downloader.py", line 17, in <module>
    retryPolicy = Retry(
TypeError: Retry.__init__() got an unexpected keyword argument 'backoff_max'
```

Possibly introduced by https://github.com/databricks/databricks-sql-python/commit/185ff3c74a126405f9aecd3c80f67ce2a22cca4e cc @kravets-levko 

I was trying to test it would help for https://github.com/databricks/databricks-sql-python/issues/383

**Comment by kravets-levko** [comment]
Hi @rth! What it the `urllib3` version installed on your machine?

**Comment by kravets-levko** [comment]
Yep, seems this parameter was added in `urllib3` v2.0.5, while we allow >=1.21.1. Thank you for reporting, I'll fi this ASAP

**Comment by rth** [comment]
> What it the urllib3 version installed on your machine?

Thanks! I had requests 2.28.2 and urllib3 1.26.19 

> while we allow >=1.21.1.

The minimal requests version should probably be increased as well, as they allow a narrow range of urllib3 version, so say requests 2.28.2  [cannot be installed with  urllib3 v2.0.0](https://github.com/psf/requests/blob/v2.28.1/setup.py#L64)

In any case I confirm that using a recent requests/urllib3 version fixes this particular error. Thanks!

**Comment by kravets-levko** [comment]
Probably I will not restrict urllib3 version to >=2.0.0, but instead just omit that option - the default value looks reasonable enough
